sudo: true
dist: trusty
language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - libopencv-dev
      - libqt4-dev

script: 
    - mkdir -p build && cd build
    - cmake .. 
    - make

notifications:
  email: false
